### ISSUE TITLE
Code rewrite

### ISSUE THREAD

**Issue by Ecconia** [mastercake10/TelegramChat#10]
Halölle,
Cool das es dieses Plugin schon gibt, muss man es nicht selber schreiben :)
Da github, internet, international und so mach ich mal auf Englisch weiter.

Hey,
I intended to use your plugin, but *sadly* I have issues with your coding style. :P
I refactored the whole plugin. You can find it at my fork branch "RefactoredCode"

The functionality is mainly the same - I think the command success messages are both green now.
There is no custom no-permission message anymore.
Oh and I ditched Metrics, since I didn't like the adapter to the API, well can be added easily again.

Refactoed:
- I removed (I think) all static accesses and added getters and setters instead.
- Change the code style here and there.
- More up to date usage of the Bukkit API. (Wrong or weird usage replaced)
- My style code formatting.

Its up to you, if you want to change your plugin according to my refactored version. In my opinion its better coding style - but that is personal preference I guess.
Sorry, my commit messages are a bit messy - but at least every change is given in small steps, one should understand them.

One more thing, I am unsure if you own the domain linus122.de which you use as package name, there is no entry registered at denic. If you really do not own it, you should use for example your github account com.github.mastercake10. But up to you.

I cannot use the plugin as it is for following reason (real Issues):
- Constant connection spam on console, every few second :O Why? (Will only show updated state)
- Two commands (Will merge them)
- Public chat (Will require the key for reading too)
- Input chat formatting (No config value)
- Listeners are constantly registered (Will only enable them when the connection is established - probably)
- öööö... joa das isses erstmal

Thanks for making this plugin, I hope I can help improving it~.
I will adjust it to my needs though. If you like to ask me things, I am available here :)

Greeting Ecconia

**Comment by mastercake10** [comment]
Hey there,

At first, I would like to thank you for your contribution to TelegramChat. I really appreciate your work on it and that you spent obviously so much time on it. You're right with the bad implementation of the Bukkit-API, since the main functions of the plugin are at least 2 years old. 
I don't agree that my coding style is that bad, but yeah, this depends on the viewer. However, we should try to keep a uniform coding style in this repository. Furthermore, I'm definitely not a fan of putting the curly braces below the method declaration. According to the Java code conventions of Oracle, you should put them just after the declaration. You can do that in C/C++, but please don't do that in Java. I know that my code breaks a lot of conventions too, but you're mainly committing this cause of the refactoring I guess.
The package name de.linus122 only represents my in-game name and the country I live in, it was never intended to be a reference to the linus122.de domain.
Moreover, the metrics are highly functional, therefore I see no reason for removing it.
Apart from these facts, I'll try to consider some of your changes in the next few releases. Yes, the connection spam is definitely an issue that should be fixed immediately.

Vielen Dank nochmal,
mastercake

**Comment by Ecconia** [comment]
Okay cool~ 
I will use it as base and maybe I finish something which I am happy with this night.

Well I did never intend that you take the code as is. So no problems with the convention.
-> I have a formatter setting, if I need something else its just changing that and applying.
Whatever~~

So tomorrow you will find more ideas in it :) 
But that could be very different from the original code.

*Edit: I was referring to your code style, not your code formatting. Confusion :D

**Comment by Ecconia** [comment]
I also had the issue that for some reason the bot constantly disconnected.
Printing the error code I got 409 errors: "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
-> If I like before updated it with 20L repeat rate, it would trigger that - 50L too.
60L is fine and doesn't throw errors.
Lowering the repeat rate may also help with your code.

**Comment by Ecconia** [comment]
Okay - I removed all spam issues.
The original code called the getUpdate method every "20L".
That caused the getUpdate method to be called with the same update_id multiple times.
The server doesn't seem to like that and returns 409 Error codes.

To prevent this from happening, block new getUpdate calls until the last one has finished.
With an update frequency of "10L" every second, you have no issues at all then.
Works perfectly for me :)
