### ISSUE TITLE
not possible to link group chats

### ISSUE THREAD

**Issue by SimJoSt** [mastercake10/TelegramChat#3]
Hi.

Awesome plugin. Very helpful to get notifications, if someone joins the server.
I added my Telegram bot to a group chat and it displayed all messages of the Minecraft-Server-Chat like charm.

Unfortunately, it was not possible for me to link the group chat.
I tried sending the "auth-code" I received by typing `/linktelegram` in-game into the group chat, but it did not have any effect.
I also linked my Telegram-Account in a private conversation with the bot and then wrote a message in a group chat the bot was part of, no luck.

Is this feature just not supported or is it a bug? If so, I will gladly supply you with the error logs and configuration, if you decide to help me.

Thanks,
Joda.

PS: We can discuss this in German as well :-)

**Comment by mastercake10** [comment]
Should have been fixed.

**Comment by fajfer** [comment]
doesn't work for me as well, the behavior is exactly as stated by @SimJoSt

**Comment by fajfer** [comment]
One thing that is probably important and didn't see mentioned in the README.md - you need to setup bot (via Botfather) privacy permissions to *disabled*, so the bot can read messages from the group

EDIT: Saying README.md was pretty much an exaggeration, I meant bukkit FAQ pages etc.

**Comment by mastercake10** [comment]
Fixed, new release can be found here: https://github.com/mastercake10/TelegramChat/releases/tag/1.0.16.
Please let me know if this really fixes the issue.

**Comment by fajfer** [comment]
I can write from Telegram to the Minecraft chat but it doesn't seem to work the other way around, anything else I could be missing? The bot still writes to me privately with chat updates but doesn't for the group. It correctly reads what I'm writing to the chat though, but didn't send me a message informing me that I successfully linked it

**Comment by fajfer** [comment]
New thing I noticed - any other group user keeps writing as my telegram linked user

**Comment by mastercake10** [comment]
I think I've found the problem - I haven't really paid attention when it comes to the linking of a group chat. For private chats, I would just link the `chat id` to the `mc uuid`. This of course doesn't applies for group chats, since we need to find out which UUID actually sends the message from telegram to mc. So I am using the `user id` instead.

https://github.com/mastercake10/TelegramChat/releases/tag/1.0.17
I hope this solves the issue.

**Comment by fajfer** [comment]
It actually interprets my messages correctly, it seems like it doesn't report messages from game to Telegram now though, tinkering with it as we speak

**Comment by fajfer** [comment]
I fixed the game messages to Telegram by resetting the data, it still doesn't work as intended I think, because IMO it should also broadcast messages on group chat as well instead of writing privately to the user (eg. if you add bot to some channel it'll keep messaging this channel) - unless I am mistaken
